using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CouponManager.Api.Migrations
{
    /// <inheritdoc />
    public partial class FixCouponsIdIdentity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql(@"
                    DO $$
                    DECLARE
                        next_id bigint;
                    BEGIN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO next_id FROM ""Coupons"";
                        EXECUTE format(
                            'ALTER TABLE ""Coupons"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                            next_id
                        );
                    END $$;
                ");
            }
            // SQLite: no-op. INTEGER PRIMARY KEY already auto-fills via ROWID.
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql(@"ALTER TABLE ""Coupons"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;");
            }
        }
    }
}
